lib/redisdriver.js
When you delete the oplog completety it was throwing an error 'Oplog is returning incorrect ops' crashing the server. Instead it should just return a callback with an error crashing only the client.
=> Prevent oplog error from crashing the server

test/client/query-subscribe.js
The pollDebounce tests insert 10 documents and make sure
that debouncing leads to two separate chunks of documents
being passed through the 'insert' callback on the query.
The problem was that we weren't waiting for the document
creation to be submitted before sending the next document.
Even though the original test behavior was a more accurate
representation of what a real client would do, it lead to
unpredictable results. The timing of when the op was submitted
could have lead to all of the documents being added in one single
chunk, rather than two.
While at it, made the test more strict -- it now checks the sizes
of the two chunks passed through the 'insert' callback, rather
than just the number of chunks.
=> Fix flaky pollDebounce tests

lib/agent.js
This way, op objects won't change form later when properties
are assigned. This makes the objects be optimized as structs
in V8.
=> Initialize op objects with all properties

lib/agent.js
Here's what server logs look like when an error is sanitized:
```
Sanitizing stack trace from error: server 192.168.99.100:27017 sockets closed
MongoError: server 192.168.99.100:27017 sockets closed
at Server.destroy (/Users/avital/tmp/sharedb-mongo/node_modules/mongodb/node_modules/mongodb-core/lib/topologies/server.js:1074:47)
at Server.close (/Users/avital/tmp/sharedb-mongo/node_modules/mongodb/lib/server.js:417:17)
at Db.close (/Users/avital/tmp/sharedb-mongo/node_modules/mongodb/lib/db.js:357:19)
at /Users/avital/tmp/sharedb-mongo/index.js:173:11
at DB.ShareDbMongo.getDbs (/Users/avital/tmp/sharedb-mongo/index.js:111:26)
at DB.ShareDbMongo.close (/Users/avital/tmp/sharedb-mongo/index.js:170:8)
at Backend.close (/Users/avital/tmp/sharedb/lib/backend.js:51:11)
at Context.<anonymous> …
```
=> Sanitize but log stack traces from errors sent to client

lib/backend.js, lib/db/index.js, lib/db/memory.js, lib/query-emitter.js, lib/submit-request.js, test/client/submit.js, test/db-memory.js, test/db.js
This needs be changed in concert with sharedb-mingo-memory and sharedb-mongo. Just merging for now and will fix the dependencies
=> add options argument to all DB public methods that read or write from snapshots or ops

lib/agent.js, lib/client/connection.js, lib/client/doc.js, test/middleware.js
Rolls back changes that added options to ops, because this is non trivial to implement and we probably need a different API for it. It won't work as expected if ops are composed. There are perhaps good ways to do this, but punting for now as this is not high priority currently.
Keeping the options format change to create, del, and submitOp doc methods, because having source as an option rather than an argument is more clear and allows for further extension.
=> remove op.options implementation; maintain change to options in doc methods

lib/agent.js, lib/backend.js, lib/submit-request.js, test/middleware.js
Adds options argument to Backend::submit, which sets the options on the submit request passed through submit / apply / commit middleware and ultimately passes options to db.commit.
Clients don't have a good way of passing this in directly when they create ops, but this does create the ability for users to add the options in middleware.
No such options are currently defined, but one could imagine that this would enable DB adapters to expose the write options of their underlying DB drivers.
=> Backend::submit options argument

lib/db/memory.js, test/db.js
By default, DB adapters should not return metadata on snapshots or ops, as this is not sent to clients and is intended only for use in debugging on the server or custom user extension. Updates the built in MemoryDB adapter to behave this way.
Also adds the option and tests that DB adapters should support to return this metadata if requested.
=> Add support for {metadata: true} option on all DB methods that get snapshots or ops

README.md
Readme.md references MemoryPubSub as a database adapter, I think it's supposed to be referencing MemoryDB
=> README.md database adapter discrepancy

lib/backend.js, test/middleware.js
A quick PR which adds the missing unit test from #69.
Allows code such as:
```
backend.use("submit", function(shareRequest, next) {
console.log("submit");
next();
})
.use("query", function(shareRequest, next) {
console.log("query");
next();
});
```
=> Chaining with `use` method

lib/backend.js
To allow:
backend
.use( "submit", function( shareRequest, next ){
console.log( "submit" )
next()
}
)
.use( "query", function( shareRequest, next ){
console.log( "query" )
next()
}
)
=> Chaining backend.use calls

examples/leaderboard/package.json
Closes #116 
This is the result from `npm install -S sharedb-mingo-memory`. After this install, the demo worked correctly for me.
=> Add missing leaderboard dependency

lib/client/doc.js, test/client/submit.js, test/ot-mock-serializable-json0.js
This pull request is an attempt to add support for custom serialization of OT types per @nateps elegant proposal as outlined here https://github.com/share/sharedb/pull/108#issuecomment-242883994.
>  The type API changes would be:
> 
> 1. Apply is overloaded to take either serialized data or deserialized data: apply(serializedData, op) -> serializedData' and apply(deserializedData, op) -> deserializedData'. Internally, the version that deals with serializedData can call deserialize on the input and serialize on the output to start with.
> 2. Add: deserialize(serializedData) -> deserializedData
> 3. Add: createDeserialized([initialData]) -> deserializedData
> 
> And the changes to ShareDB would be:
> 
> 1. Doc::ingestSnapshot should call type.deserialize before setting doc.data if defined
> …
=> custom serialization of OT types (Nate's proposal)

README.md
I noticed that the README was missing documentation for `doc.ingestSnapshot`, so I copied it over from the source into the README.
=> Add documentation for ingestSnapshot

README.md
`doc.whenNothingPending` can be quite useful in application code, and I noticed it was not documented, so I thought I'd add some documentation for it.
=> Add documentation for doc.whenNothingPending

README.md
I faced a need to use this, as after invoking `doc.destroy()`, then invoking `doc.subscribe` from elsewhere, the listeners added before the call to `doc.destroy()` were still being invoked.
=> Add documentation for doc.removeListener

README.md
=> Add documentation for Projections

examples/rich-text/static/index.html
Adding Responsive Meta Tag
`<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>`
This will be desirable for all mobile devices
=> adding responsive meta

README.md
Avoid cluttering the feature list with links by linking to the pub/sub adapter section with more details.
=> Reorganize pub/sub adapter listings

lib/client/connection.js, test/client/connection.js
Before this PR the connection event sequence could be like:
1. connected
2. disconnected
3. connected
when using a plain `WebSocket` and `bindToSocket` in a browser. If some kind of reconnecting socket were used (without `bindToSocket`), you might get the `connecting` events, too.
After this PR is merged, the `connecting` event would be emitted consistently regardless of the socket implementation, for example:
1. connecting
2. connected
3. disconnected
4. connecting
5. connected
=> Always update connection state using _setState

examples/leaderboard/server/index.js
This PR removes a variable that is defined, but not used.
Verified that the behavior of the example remains the same.
=> Remove unused Duplex variable in example

examples/leaderboard/README.md
When trying to run this example locally I noticed the instructions were a bit confusing. Just added a bit of clarity.
=> Make example instructions in readme a bit more clear

lib/client/connection.js, test/client/connection.js
* Fixed a couple spelling mistakes in a comment
* Added very simple state unit tests for Connection state
* Add additional tests for bindToSocket that check:
* connection.state should be connecting if socket.readyState is 0 or 1
* connection.state should be disconnected if socket.readyState is not 0 or 1
=> Add state management tests for connection

.travis.yml, lib/pubsub/index.js, lib/submit-request.js, test/pubsub-memory.js, test/pubsub.js
This PR fixes the issue where the entire server crashes when ShareDB fails to publish a message to its PubSub system.
The easiest way to reproduce the problem is to use Redis for PubSub (with node-redis configured to try to restore the connection indefinitely), stop Redis and then send some operations to ShareDB server. ShareDB will then try to publish a message to Redis and crash the server.
The fix is to simply add an empty callback to the `publish` function. This works fine as ShareDB can gracefully recover from losing those messages by reading the missing document revisions from the database (eg MongoDB). For the same reason I don't think it is necessary to propagate the publishing error up, although it certainly is a possibility.
=> Fix server crashing on failed publish

.gitignore, README.md, lib/backend.js, lib/projections.js, test/middleware.js
* Trigger `queryDocs` or `docBulk` middleware action when many documents are fetched at once. * Only trigger `doc` action when retrieving a single doc.
*WIP*
There are no tests, this is not ready for merging. I would like feedback on the general approach before I dive into testing and making this more production ready.
=> Add new middleware events for document reads

README.md, lib/backend.js, lib/projections.js, lib/query-emitter.js, test/middleware.js, test/util.js
Upon further reflection and thanks to advice from @l8on and @ericyhwang, simplify read middleware API to single `readSnapshots` middleware action. Update tests accordingly.
Also, since we moved to camelCased actions, rename `after submit` to `afterSubmit` and shim space delimited action name by default for initial backwards compatibility until a future major version.
=> Read docs middleware

README.md, examples/textarea/client.js, examples/textarea/package.json, examples/textarea/static/index.html
I updated the **textarea** example and updated the readme about how to handle reconnections.
=> Reconnecting Websocket Example and Updated Readme

.travis.yml, package.json, test/client/submit.js
See https://github.com/mochajs/mocha/releases/tag/v5.0.2.
The tests were failing because mocha@5.0.2+ crashes on unhandled exceptions resulting from unhandled "error" events. Earlier versions ignored those exceptions.
@ericyhwang this PR would also enable us to use the latest mocha version in sharedb-mongo.
=> Update mocha and fix 2 tests

.travis.yml, test/client/submit.js
This is a slightly speculative fix for a test that fails intermittently
on `sharedb-mongo`. I believe these intermittent failures are due to a
race condition in a concurrency test.
The test works by attempting to fire two commits off at the same time,
and hoping that one of them is committed just before the other, so that
a `SubmitRequest.retry` is triggered whilst the `maxSubmitRetries` is
set to `0`, resulting in an error that is expected.
However, I believe it's possible for these commits to (in some cases)
happen sequentially rather than concurrently, and fail to error.
This change attempts to force them into this retry condition by:
- Catching both ops in the `commit` middleware, _just_ before they're
about to be committed (and hit a `retry` if applicable)
- Waiting until both ops …
=> Fix flaky maxSubmitRetries test

.travis.yml, lib/client/doc.js, test/client/subscribe.js
It fixes the issue where a document is re-added to a collection after calling `destroy`, causing a memory leak.
It should also fix https://github.com/share/sharedb/issues/161.
Re not waiting for the unsubscribe callback in `destroy`, I think it is not necessary because:
- unsubscribe cannot fail on the server side (as far as I see),
- unsubscribe is performed automatically on disconnect,
- the doc is marked as unsubscribed immediately on the client side.
=> Fix Doc.prototype.destroy

.travis.yml, package.json, test/client/query-subscribe.js, test/db-memory.js
sharedb had depended on sharedb-mingo-memory for 4 tests, mostly relating to query subscriptions. This removes that dependency by faking out enough of MemoryDB in the tests to handle simple queries. (MemoryDB itself returns all documents in a collection given a query.)
I didn't want to put the simple query handling in MemoryDB, as that might lead people to think it may do more than it can. We don't want to re-implement all of Mingo, either.
=> Remove sharedb-mingo-memory circular dependency

.travis.yml, README.md, lib/backend.js
I've also removed `doc` from README.md because the other deprecated action, "after submit" was not there either.
=> Warn about using deprecated features

lib/backend.js, lib/query-emitter.js, test/client/snapshot-request.js
In the `readSnapshots` middleware, it's currently impossible to
determine whether a snapshot is being returned as the result of a
`fetch` or a `fetchSnaphot`.
This change adds a version `v` field to the `request` when the
middleware is invoked from `fetchSnapshot`. This field is populated with
the value of the requested version, and can be used to determine that
the snapshot is the result of a `fetchSnapshot` rather than a `fetch`.
=> Expose `fetchSnapshot` requested version in `readSnapshots` middleware

README.md, lib/backend.js, lib/client/snapshot-request.js, lib/milestone-db/index.js, lib/milestone-db/memory.js, lib/milestone-db/no-op.js, lib/util.js, test/milestone-db.js
This change updates our `MilestoneDB` base class to be an empty shell
that throws whenever any of its methods are called in order to help
implementers.
We then also introduce a `NoOpMilestoneDB` implementation, which
implements all the methods, but does nothing. This is so that we can
drop this implementation into the `Backend` as a sensible default that
does nothing at all when called (instead of eg using `MemoryMilestoneDB`
and having the surprising behaviour of working until you restart your
application).
As part of this, the base call signature of the `saveMilestoneSnapshot`
callback is changed to remove the `wasSaved` flag. A snapshot should be
assumed to have saved if no error is returned in that callback.
=> Add a `NoOpMilestoneDB` implementation

lib/client/snapshot-request.js, test/client/snapshot-request.js
This change improves `SnapshotRequest` test coverage to 100%.
Our current test for checking that a dropped connection works didn't
actually fail properly when removing `this.sent = false` from
`SnapshotRequest._onConnectionStateChanged`, so an improved test has
been written that use middleware to wait until the request has
definitely been sent, before dropping the connection and reconnecting.
It also adds a previously uncovered test case for checking that the
connection cannot send the same request multiple times, by using a
similar setup to the rewritten dropped connection case.
This change also adds some documentation recording why we might want to
reset `this.sent = false`, because just looking at the code it's
unclear why we would ever want to do that.
=> Improve test coverage for `SnapshotRequest.onConnectionStateChanged`

README.md
the `reconnecting-websocket` url is not right
=> Fix: correct a link of README

README.md, lib/agent.js, lib/backend.js, lib/client/connection.js, lib/client/doc.js, lib/client/index.js, lib/index.js, lib/logger/index.js, lib/logger/logger.js, lib/stream-socket.js, test/logger.js
Fixes https://github.com/share/sharedb/issues/250
Supersedes https://github.com/share/sharedb/pull/252
This change adds the ability to override ShareDB's logging behaviour.
By default, ShareDB will still log to `console`. However, this default
can be overridden with custom methods on both the backend and in the
client.
The ShareDB logger only supports the following methods:
- `info`
- `warn`
- `error`
Any method that is not overridden will default to `console`.
The backend methods can be overridden when instantiating `Backend`:
```javascript
var share = new Backend({
logger: {
info: () => {},                         // Silence info
warn: () => alerts.warn(arguments),     // Forward warnings
error: () => alerts.critical(arguments) // Map errors to critical
}
});
```
Client methods can also …
=> Allow custom logger overrides

lib/client/doc.js, test/client/doc.js, test/client/submit.js
Fixes https://github.com/share/sharedb/issues/257
As outlined in the above issue, calling `Doc.submitOp` can sometimes
`throw` a synchronous error, for example when submitting an invalid op
that causes `type.apply` to `throw`.
This is surprising behaviour, because an error handler should already be
provided in the callback supplied to `submitOp`. What's more, the doc
could be left partially mutated and out-of-sync with the server, which
could lead to confusing behaviour.
This change wraps all internal usage of `Doc._otApply` in `try`/`catch`
blocks. If an error is thrown in this method, then we attempt to
recover with `Doc._hardRollback`, which will attempt to reset the
document and then call the callbacks of the pending ops with the error.
This change also prevents `Doc._hardRollback` …
=> Catch synchronous errors in `Doc._otApply`

lib/agent.js, test/client/connection.js
When we subscribe to the same stream sharedb leak, because of the cross reference between the stream and the agent the leak is even more critical.
close #260
=> fix leak on duplicate subscription - #260

examples/textarea/client.js, examples/textarea/server.js
This textarea example was initially confusing for me as I could not understand initially how to assign the textarea value to the property within the document without reading documentation multiple times to provide the path. 
This pull request hopes to address that: By making it more clear to access the property of the document and assigning the value within the HTML textarea to that property of the document instead of assigning it as the raw data value for the document.
This makes it a bit more intuitive for those getting started with using sharedb for co-editing components within their web applications to see how one can use the textarea as an element of choice.
=> Making textarea example more clear by assigning the textarea value to the property of a document, rather than directly to the document.

lib/backend.js, test/client/snapshot-timestamp-request.js, test/middleware.js
When monitoring for unusual response sizes, it can be useful to record which client request was associated with the response. Unfortunately, ShareDB's current "readSnapshots" middleware, which is how you get info about snapshot responses, doesn't contain information about the associated request.
This PR adds a couple additional fields to the "readSnapshots" middleware's `request` param, `method` and `parameters`.
The "readSnapshots" middleware function now has a first parameter `request` like this:
```javascript
function(request, next) {
let {
collection,
snapshots,
method,  // Backend.prototype.READ_SNAPSHOTS_METHODS: 'fetch', 'query', etc.
parameters,  // Plain JS object, shape varies depending on method
snapshotType,  // Backend.prototype.SNAPSHOT_TYPES
agent
} = request;
}
```
=> For readSnapshots middleware, add method and parameter properties to first parameter

lib/backend.js, test/client/snapshot-timestamp-request.js, test/middleware.js
Reverts share/sharedb#263, as it causes issues with `'readSnapshots'` middleware for `queryPoll()` calls. The "bad" version has already been unpublished from NPM.
See https://github.com/share/sharedb/issues/269 for details.
=> Revert "For readSnapshots middleware, add method and parameter properties to first parameter"

lib/client/doc.js, test/client/doc.js
This fixes a double-callback issue for chained op submissions, where if the second op is invalid, the first op's callback gets called twice:
https://github.com/share/sharedb/issues/272
`Doc._hardRollback` [already does takes a similar approach](https://github.com/share/sharedb/blob/v1.0.0-beta.18/lib/client/doc.js#L896-L904) of clearing local Doc state prior to calling callbacks, and Nate expressed his agreement with this fix today at the PR review meeting.
Thanks to @nickasd and @alecgibson for developing the test case that reproduces the issue!
=> In Doc._clearInflightOp, clear inflightOp before calling callbacks

lib/agent.js, lib/backend.js, test/middleware.js
The "reply" middleware is called just before the backend is about to send a non-error reply to a client.
It's the flip side of the existing "receive" middleware action.
The middleware function gets a context with these properties:
- request
- reply
- action (always `'reply'` for this middleware)
- agent
- backend
=> Add new "reply" middleware action

README.md
* Add docs for new "reply" middleware action, which I forgot to add in https://github.com/share/sharedb/pull/278
* Make some tweaks to docs for the middleware listener function, to make it clear which properties are always provided and which are only provided in certain cases
=> Update middleware docs: add "reply" action, other tweaks

lib/agent.js, test/client/connection.js
The intention here is to resolve #282.
As of now this is a rough first pass. I have not tested or verified if this works yet.
@gkubisa Does this approach seem to make sense?
=> Clean up closed connections

examples/textarea/package.json, examples/textarea/server.js
Closes  #280
Since the [example in README.md uses @teamwork/websocket-json-stream](https://github.com/share/sharedb/pull/276/files), I thought it would make sense to also have the code examples use it.
There is a slight issue at the moment with this change, I'm not sure why. It's documented here [Teamwork/websocket-json-stream: Error with ShareDB Usage](https://github.com/Teamwork/websocket-json-stream/issues/3).
If we proress here, I'd like to also propose updating the other examples in the same way, then once they work, update all their dependencies generally, which are getting out of date.
Related to discussion here https://github.com/share/sharedb/issues/275
=> Use @teamwork/websocket-json-stream in textarea example

lib/logger/logger.js
in chrome 51, will throw error
=> fix: Uncaught TypeError: Illegal invocation in chrome 51

examples/counter/package.json, examples/counter/server.js, examples/leaderboard/package.json, examples/leaderboard/server/index.js, examples/rich-text/package.json, examples/rich-text/server.js
This finishes up the work started to update the README (https://github.com/share/sharedb/pull/276) and the textarea example (https://github.com/share/sharedb/pull/281).
`@teamwork/websocket-json-stream` is more actively maintained. See https://github.com/share/sharedb/issues/275 for the discussion around switching.
=> Update rest of examples to @teamwork/websocket-json-stream

README.md, lib/backend.js, test/backend.js
The database adapters allow an `options` object to be passed through to
them for enabling the return of metadata with a snapshot or ops.
Consumers could query the database directly, or even use the database
adapters, but this may give inconsistent results when comparing ops with
those fetched through `getOps`. For example, the Mongo adapter makes
sure that a valid set of ops with unique versions are returned, which
may not be the case when querying the database directly. Fetching ops
and snapshots through `Backend` methods also ensures that we call the
appropriate "sanitize" methods, and trigger the corresponding
middleware.
However, we don't expose this on `Backend.getOps` or `Backend.fetch`.
This change adds an optional `options` argument to these methods, which
can then be used to ask …
=> Allow options to be passed for `fetch` and `getOps`

README.md
This change adds `Backend` documentation to methods that provide
functionality not offered by a client.
=> Add `Backend` documentation

README.md, lib/backend.js, test/middleware.js
Fixes https://github.com/share/sharedb/issues/313
`afterSubmit` is a potentially confusing middleware hook, as it might
suggest that it takes place after an op has been submitted, but _before_
it has been processed and committed.
This change renames the hook to the slightly clearer `afterWrite` hook,
which conveys that the op has actually been written.
=> Rename `afterSubmit` middleware hook to `afterWrite`

lib/agent.js, lib/backend.js, lib/op-stream.js, lib/pubsub/index.js, lib/query-emitter.js, test/BasicQueryableMemoryDB.js, test/client/projections.js, test/db-memory.js, test/db.js, test/middleware.js
Prior to this PR, if you issue a query subscription on a projection, with a filter field that's not in the projection fields, then an op to change that filter field will not trigger the query to update.
This is because the op projection (`_sanitizeOp`) was happening prior to the `skipPoll` checks, which are what determine if an op could affect a query. A projected op would appear like it doesn't affect the query.
The fix is to defer applying projections to query ops until after the `skipPoll` checks.
I couldn't write a unit test in this repo, since the MemoryDB's query implementation always returns all docs in the collection, regardless of query filters. See below for the test I'll be adding to sharedb-mongo to cover this case.
----
Test I'll be adding to sharedb-mongo, which fails prior …
=> Support query subscriptions on projections with a filter not in the projection fields

lib/agent.js
Fixes https://github.com/share/sharedb/issues/315
At the moment, if middleware ever returns an `Error` object, its stack
trace will get dumped into `logger.warn`. This can be quite noisy,
especially if those errors are part of normal control flow (eg
authentication).
This behaviour can currently be avoided by passing just a `string` to
the middleware callback (rather than an `Error` object). However, this
is not the "standard" behaviour for callbacks, which will typically be
called with an actual `Error` object, rather than a `string` (eg Node's
[`fs` module][1]).
This change downgrades the logging from `warn` (surprising, but non-
critical) to `info` (unsurprising), so that the information is still
available to those who want it, but doesn't get the same sort of
importance assigned to it …
=> Downgrade middleware stack dump from `warn` to `info`

test/BasicQueryableMemoryDB.js, test/db.js
Implement additional BasicQueryableMemoryDB implementation methods, so that code paths in query-emitter are exercised by tests
=> add test coverage for queryPollDoc

.travis.yml, lib/client/connection.js, lib/query-emitter.js, package.json, test/backend.js, test/client/connection.js, test/client/doc.js, test/client/pending.js, test/client/projections.js, test/client/query-subscribe.js, test/client/query.js, test/client/snapshot-timestamp-request.js, test/client/snapshot-version-request.js, test/client/submit.js, test/client/subscribe.js, test/db-memory.js, test/db.js, test/logger.js, test/middleware.js, test/milestone-db.js, test/ot.js, test/projections.js, test/pubsub-memory.js, test/pubsub.js
Update dependencies to current versions:
* deep-is => fast-deep-equal, since deep-is has some correctness bugs, is much slower, and isn't well maintained
* expect.js => chai for assertions
* instanbul => nyc for generating coverage reports
* Update all dev-dependency versions to current
* Add Node 12 & remove Node 6 from travis configuration to bring current with Node LTS versions
=> Update dependencies & node versions in travis

lib/query-emitter.js, test/client/query-subscribe.js
When clients create a query subscription, ShareDB sends all ops that match documents returned by the query as well as diffs in which documents match. These results may be live-bound in the UI to a list displayed to the user.
ShareDB doesn't guarantee the sequence in which these op & query result updates will be received, but currently the code sends the ops as soon as they are received, then issues the query against the database. At this point, both the 'op' middleware and the database poll are async operations, so they could complete in either order. However, in practice ops are probably received first, since the database poll likely takes much more time than the op middleware.
This change makes it so that ops are consistently ordered after diffs in results by delaying sending of ops …
=> Delay ops sent by query subscriptions until after polling is complete

lib/agent.js, test/middleware.js
Previously, ops were copied by iterating over them in pubsub. This was changed in https://github.com/share/sharedb/pull/316 to copy the specific properties expected on an op. Copying the specific properties is faster than iterating and allows use of specifically typed objects.
However, this ended up being a breaking change, because middleware could be adding additional fields to the top level of the op, which do end up getting committed and fetched. Perhaps a way to add additional op fields explicitly should be implemented, but for now, let's just revert, since this was not intended to be breaking.
=> revert to using a simple shallowCopy for ops

test/client/query-subscribe.js
Still haven't found source of flakiness, but it appears that there is a flakey test in query subscriptions as well. This instrumentation should hopefully catch the next time it errors.
=> Add error handlers in tests to try and find source of flakey test

lib/client/doc.js, test/client/doc.js
A very rare case happens sometime to us were an operation is sent just before a deconnection, modified while disconnected, and sent again when connection is recovered. Local document assume last operation was applied, when in fact only the first one was and no error is ever raised. This happen with latest `ShareDB` + `ShareDB-Mongo`.
I traced back the issue, and here is what I understand from it:
- When a disconnection occurred while an op is inflight, the operation is put back on the stack of pending ones ensuring it is sent again when connection is recovered => [`client/doc.js#L348-L352`](https://github.com/Calyhre/sharedb/blob/d28eb71a4121eb9d9ad3b816c8093c960f5101e5/lib/client/doc.js#L348-L352)
- But this also makes it a potential candidate to be composed with when operations are …
=> Fix previously inflight op could be mutated

README.md, lib/agent.js, lib/backend.js, lib/client/connection.js, lib/client/doc.js, lib/error.js, lib/read-snapshots-request.js, lib/readSnapshots-request.js, test/client/query.js, test/client/subscribe.js
The "readSnapshots" middleware can be used to reject snapshot reads, such as for access control. However, it's currently all or nothing. When doing a bulk fetch or subscribe, the middleware receives many snapshots at once, and you currently can't reject reads for specific snapshots while allowing others through.
Bulk fetch/subscribe is automatically used on reconnection, when multiple fetches/subscribes by id are issued while a client is offline. It can also be manually triggered via the currently-undocumented `Connection#startBulk` and `#endBulk` methods.
1. Add ability for "readSnapshots" middleware to reject reads of specific snapshots for bulk fetch/subscribe
2. Fix client handling of errors in replies to bulk actions. Such errors were getting silently ignored before.
This is …
=> Add ability for "readSnapshots" middleware to reject reads of specific snapshots for bulk fetch/subscribe

test/mocha.opts, test/setup.js
At the moment, the logger will log to console during tests, which is
noisy and undesirable.
This change adds a test setup file, which silences the logger by setting
all of its methods to no-ops.
This behaviour can be overridden with the `LOGGING` environment
variable:
```bash
LOGGING=true npm test
```
=> Silence logger in tests

test/client/doc.js, test/client/snapshot-timestamp-request.js, test/client/snapshot-version-request.js, test/milestone-db.js, test/util.js
The hand-rolled `util.callInSeries` method was added without realising
that the `async` library was already in use in the library.
This change removes our custom method, and simply uses the appropriate
`async` functions instead.
We also add a utility `errorHandler` function that will call `done` in a
test if an error occurs, but not otherwise, which is useful when using
callback methods in a fire-and-forget fashion.
=> Remove `util.callInSeries`

lib/client/connection.js, test/client/connection.js
In our situation, we will connect to the server and authorize the request first, so if socket is already open, we must do handshake immediately because `onopen` event will not be emitted again.
=> handshake immediately if socket is already open

README.md
The docs currently give examples with `backend.useMiddleware`, but the
correct syntax is `backend.use`.
=> Fix middleware docs

lib/backend.js, package.json
We can't upgrade to async@3 because it uses ES6 features like arrow functions, and ShareDB currently targets ES5 without needing to transpile. async@2 is still actively receiving patch updates.
In the [async@2 breaking changes list](https://github.com/caolan/async/blob/master/CHANGELOG.md#v200), the only one that would affect Share is that `each`/`parallel`/etc no longer use `setImmediate` internally.
The only place in ShareDB core that uses those with a possibly-synchronous function is `_sanitizeOps`, so I've added a `process.nextTick` in its callback to prevent the call stack from getting too big.
I considered making `Db#_sanitizeOp` or `Db#trigger` (middleware triggering) async. However, it's possible that someone may be depending on multiple middleware functions triggering …
=> Upgrade to async@2

lib/client/connection.js, lib/client/presence/presence.js, test/client/presence/presence.js
This change fixes the following edge case:
1. Create a `Presence` object
2. Subscribe the presence
3. Destroy the presence
4. Create a new `Presence` object for the same channel on the same
`Connection` object
5. Attempt to re-subscribe
6. `Agent` ignores the re-subscribe request, because the `seq` was
reset to `1` on the new `Presence` object, but is still `2` on the
`Agent`
We fix this by using a universal `_presenceSeq` counter on the
`Connection`, which is never reset, meaning that all presence messages
will have a strictly higher number than one another.
=> Fix presence re-subscribe after destroy

examples/textarea/client.js
Fixes https://github.com/share/sharedb/issues/362
The textarea example currently doesn't work, because it overrides a
bunch of our WebSocket event handler functions.
This change fixes that by attaching these methods as listeners, rather
than overriding the handler functions.
=> Fix textarea example

lib/client/connection.js, lib/client/doc.js, lib/util.js, test/client/subscribe.js
Fixes https://github.com/share/sharedb/issues/357
This change is a rework of our subscribe/unsubscribe logic. At the
moment, subscribe and unsubscribe messages are handled completely
separately, which means that we can hit race conditions when
simultaneous subscribe and unsubscribe requests are submitted.
This currently manifests itself in this bug:
1. `subscribe()`
2. `unsubscribe()` synchronously (ie before receiving the `subscribe`
response
3. Expect to finish unsubscribed. Indeed, `Doc` claims that I'm
unsubscribed, but actually - because subscribe happens to take a
bit longer on the server - I'm really still subscribed
This change reworks subscribe and unsubscribe requests into a queue:
- there may only ever be a single in-flight subscribe or unsubscribe
request
- other requests are …
=> Only allow a single subscribe/unsubscribe request to be in-flight

.gitignore, test/client/subscribe.js
Background: sharedb's tests get included and run inside of sharedb-mongo as well.
https://github.com/share/sharedb-mongo/pull/88 revealed that the new test case added in https://github.com/share/sharedb/pull/358 for "unsubscribes synchronously" doesn't work in sharedb-mongo's test suite, which has a DB connection per test case and closes that connection after the test. The second client's op submission then results in:
```
Error: Already closed (and Mocha's done() called multiple times)
```
This PR moves the `done()` in the test to after the second client has successfully submitted. If the first client is incorrectly still subscribed and receives the op through a subscription, that will still correctly cause the test case to fail with "Already closed (and Mocha's done() called multiple …
=> Fix test for sync unsubscribe, to work with real DB (sharedb-mongo)

.travis.yml, after-script.sh
This change runs the [`sharedb-mongo`][1] test suite as part of the
Travis build, since `sharedb-mongo` pulls some tests directly from this
library.
[1]: https://github.com/share/sharedb-mongo
=> Run `sharedb-mongo` tests

lib/agent.js, lib/client/connection.js, lib/client/doc.js, lib/ot.js, lib/projections.js, package.json, test/client/submit-json1.js, test/client/submit.js, test/db.js
Hi!
This is a fix for https://github.com/share/sharedb/issues/373
I chose to use `'op' in op` as the check to know if we are doing an edit.
I've added a simple test to verify that it works (it was actually really useful to find all the places I needed to change).
=> Allow an op to be falsy

test/client/submit-json1.js
At the moment, we have a test that has a race condition. We submit ops
synchronously from two different connections, but it's not well defined
which of these will be committed first.
This change waits for the first submission to be acknowledged before
firing the second submit op. We still test the server `transformOp`,
because `doc2` is not subscribed (and hence submits an op at a version
behind the current snapshot version, which will need transforming).
We also fix the fact that the two ops previously did not combine into a
no-op by just firing off a redundant prop removal as the second op.
=> Fix flaky test

lib/client/presence/local-doc-presence.js, test/client/presence/doc-presence.js
When we destroy local presence, we attempt to update the presence to
`null` for remote clients as part of the cleanup.
However, if we delete a doc, and then destroy the associated presence,
the presence attempts to send a message on a deleted doc, which returns
an error.
Let's just ignore this error. There's no need to reset presence on a
deleted doc, because remote clients will [already assume it's `null`][1].
[1]: https://github.com/share/sharedb/blob/a81e2c99af77da12885f0fa860e87cc2602a6cc1/lib/client/presence/local-doc-presence.js#L90-L96
=> Ignore doc does not exist on presence destroy

README.md, lib/client/doc.js
This change:
- initialises `doc.paused` with a value
- adds some documentation to the variable
- adds the `pause()` and `resume()` methods to the `README`
=> Document `pause` and `resume`

lib/agent.js, lib/submit-request.js
Since `backend.MIDDLEWARE_ACTIONS` is defined in `Backend.prototype`, it's better to use it as an action name.
=> fix: replace action name with backend.MIDDLEWARE_ACTIONS

README.md, lib/client/doc.js, test/client/doc.js
This change adds two events:
- `before op batch` - fired once before any set of ops is applied.
- `op batch` - fired once after any set of ops is applied. This may
follow multiple `op` events if the op had multiple `json0` components
This is a non-breaking change that should allow clients to process ops
in their entirety.
There has already been some discussion around this:
- https://github.com/share/sharedb/pull/129
- https://github.com/share/sharedb/issues/396
This is a much simpler approach than the existing pull request. Here we
try not to change existing behaviour, and only add new, non-breaking
events.
Motivation for such an event would include clients applying some form of
validation logic, which doesn't make sense if an op is shattered.
For example, consider a client that wants to …
=> Add batch op events

.mocharc.yml, package.json, test/mocha.opts
This change bumps `mocha` to the latest version. v8 [dropped support][1]
for `mocha.opts`, so we replace it with a `.mocharc.yml` config file
instead.
[1]: https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-changes
=> Bump mocha

lib/client/connection.js, test/client/connection.js
At the moment, it's possible for the server to miss the client's `hs`
handshake message. Since it never gets the handshake, it never sends one
back, and the client remains uninitialised.
This can happen when performing asynchronous, long-running tasks between
opening the websocket, and calling `backend.listen` to bind the socket
to ShareDB.
This change fixes this issue by having the client send the handshake
message twice:
- Once when the `Connection` is initialised. If the server is ready,
but the client connected late, we'll still handshake.
- Once when the client receives the server's `init` message. If the
server bound to the socket late, and missed the first handshake
message, this prompts us to send it again.
=> Send client handshake when server binds

test/db.js
We should be able to call `db.close()` even after the database has
already been closed, and not get an error.
This change adds a test for this case.
=> Test for calling `db.close()` multiple times

README.md, lib/agent.js, lib/client/connection.js, lib/client/doc.js, lib/submit-request.js, test/middleware.js
This change adds the capability to send an op's `source` to the server,
for access in middleware.
The use-case that inspired this change was the ability to record some
usage stats based on users' ops. It's possible to record these stats
through separate HTTP calls, but recording stats through ShareDB would:
- keep stats in sync with committed ops
- allow servers to dictate stat definitions (enabling immediate
roll-out; consistency; etc.)
- leverage existing socket connections, which prevents having to open
another socket; make lots of HTTP calls; or resort to
[`sendBeacon`][1]
However, the type of stats we wish to record require more transient
information about the source of the op (eg keyboard; clipboard; mouse;
etc.).
It's clearly impractical to set this at connection time (where we set …
=> Optionally send `source` to the server

README.md, lib/backend.js, test/backend.js
This change adds a new `after submit` event at the end of an op
submission, *regardless of success*.
At the moment, we have:
- `submit`: called when an op is submitted
- `afterWrite`: called after an op is successfully committed to the
database
- `reply`: called when the `Agent` is about to send a non-errored
reply back to the client
However, it's currently impossible to react to ops that error, or to
ensure that you catch an event whenever an op is finally "done"
processing, regardless of success or failure.
=> Add hook for end of op lifecycle

.eslintrc.js, lib/agent.js, lib/backend.js, lib/client/connection.js, lib/client/doc.js, lib/client/presence/local-presence.js, lib/client/presence/presence.js, lib/client/presence/remote-presence.js, lib/client/query.js, lib/db/memory.js, lib/milestone-db/index.js, lib/milestone-db/memory.js, lib/milestone-db/no-op.js, lib/pubsub/index.js, lib/pubsub/memory.js, lib/stream-socket.js, lib/util.js, test/util-test.js
Fixes https://github.com/share/sharedb/issues/255 & https://github.com/share/sharedb/issues/427
At the moment, ShareDB uses the Node.js `process.nextTick` everywhere,
including in client-side code.
ShareDB's current advice is to use a modern build-chain tool, such as
Webpack or Browserify to add support for these Node.js functions.
However, Webpack v5 has [removed][1] their Node.js polyfills. Webpack
actively recommends package authors to "provide alternative
implementations/dependencies for the browser."
It's now quite weird that ShareDB forces consumers to polyfill the
entire `process` module, when we really just need `nextTick`. In order
to keep ShareDB usage as simple as possible, this change ponyfills
`process.nextTick`:
- If `process.nextTick` is already defined, we just use this …
=> Ponyfill `nextTick`

lib/util.js
Still seeing an issue with Webpack v5 even after #434.
`process` is undefined in a browser environment, so `if (process) ...` will throw a reference error. A check with `typeof` needs to be used instead.
Couldn't come up with a way to unit test this differently.
=> fix for process being undefined in browser environment

docs/api/backend.md
Markdown renders a pipe as a table divider, which wasn't what was
intended here, so let's escape it.
=> 📝 Escape pipe

docs/adapters/database.md, docs/adapters/milestone.md, docs/adapters/pub-sub.md, docs/api/agent.md, docs/api/backend.md, docs/api/connection.md, docs/api/doc.md, docs/api/local-presence.md, docs/api/presence.md, docs/api/query.md, docs/api/sharedb-error.md, docs/api/snapshot.md, docs/document-history.md, docs/getting-started.md, docs/middleware/index.md, docs/presence.md, docs/projections.md, docs/pub-sub.md, docs/types/index.md, docs/types/json0.md
According to the [Jekyll docs][1]:
> Since Jekyll 4.0 , you don’t need to prepend `link` and `post_url`
> tags with `site.baseurl`
However, Github Pages is [stuck on v3][2], so we need to prepend all of
our links with `site.baseurl`.
Note that we could potentially just move to using relative paths
(rather than using the `link` tag), but the `link` tag offers some solid
benefits:
- fails build if the linked page doesn't exist
- keeps paths relative to the root, which makes updating links much
easier (eg find-and-replacing a moved file)
[1]: https://jekyllrb.com/docs/liquid/tags/#links
[2]: https://github.com/github/pages-gem/issues/651
=> 📝 Fix links

README.md, docs/Gemfile, docs/Gemfile.lock, package.json
This change adds helper scripts to our `package.json` for working on the
documentation, as well as a brief overview in the `README`.
=> 📝 Add docs development scripts

test/client/projections.js, test/client/query-subscribe.js, test/client/query.js, test/db.js
Implementing queries is technically optional for database adapters.
This change updates our `Db` test suite to:
- check if `getQuery` has been passed in the options
- remove MongoDB-specific `getQuery` mapping
=> ✅ Make `getQuery` optional in `Db` test suite

lib/backend.js, lib/query-emitter.js, lib/submit-request.js, test/backend.js, test/middleware.js
Fixes https://github.com/share/sharedb/issues/454
We recently made [a change][1], which added checks for if `agent` was
provided to certain backend methods. This added unofficial support for
a falsy `agent`, which we don't really want to support.
This change removes these checks, and fixes the tests that fail because
they pass in a `null` agent.
Note that we discussed adding a formal assertion, but this pattern
didn't fix with the existing methods, which all operate under the
assumption that its arguments are present.
[1]: https://github.com/share/sharedb/pull/446
=> 🥅 Remove agent truthiness checks

docs/document-history.md, docs/middleware/index.md, docs/presence.md, docs/queries.md
This change adds some documentation around how to use queries, along
with some notes on performance.
We also add the `query` hook to our middleware documentation.
=> 📝 Add query documentation

docs/_config.yml
This change updates our [config][1] to:
- add a link to the Github repo in the top-right corner
- add a link to the current page in Github at the bottom of the page,
encouraging viewers to edit the page
[1]: https://pmarsceill.github.io/just-the-docs/docs/configuration/
=> 📝 Add auxiliary links

examples/counter-json1/package.json, examples/counter/package.json, examples/leaderboard/package.json, examples/rich-text-presence/package.json, examples/rich-text/package.json, examples/textarea/package.json
Fixes https://github.com/share/sharedb/issues/466
Running the example `build` commands on windows doesn't work, because
`mkdir` [fails with the wrong slash type][1].
However, `browserify` will already [ensure the directory exists][2], so
we don't even need this command.
This change removes our call to `mkdir`, and also simplifies the call
to `browserify`, since `node_modules` is already on the PATH when run
with `npm run`.
[1]: https://stackoverflow.com/a/52863346/4003671
[2]: https://github.com/browserify/browserify/blob/0ec6e80ec48b67513718a392a6d09bd5569967d4/bin/cmd.js#L64
=> 🔨 Fix example script builds on Windows

docs/queries.md
When you create a subscribe query, the query will automatically pass all
ops [back to the client][1], regardless of whether the doc wants to be
subscribed or not.
This change fixes our docs on this matter.
[1]: https://github.com/share/sharedb/blob/fb1b0850019cdb0cb6a59efcfd75811b27317bf0/lib/query-emitter.js#L105
=> 📝 Fix query documentation

lib/client/presence/local-doc-presence.js, test/client/presence/doc-presence.js
At the moment, if a consumer tries to listen for presence on a type that
does not support presence, they'll get an error along the lines of:
```
TypeError: this._doc.type.transformPresence is not a function
at LocalDocPresence._transformAgainstOp
```
This can be a bit confusing for consumers who assume their type supports
presence.
This change wraps that method in a function that will check if the type
supports presence. If not, then we throw a more descriptive error,
explaining that the type does not support presence.
=> 🥅 Improve presence error message

.github/workflows/test.yml, CHANGELOG.md
Fixes https://github.com/share/sharedb/issues/483
Node.js v10 was [end-of-lifed][1] in April 2021. This change drops
support for testing against it in our build matrix.
[1]: https://nodejs.org/en/about/releases/
=> 💥 Drop Node.js v10 support

lib/backend.js, test/backend.js
This is required for downstream middleware.
Tests done and passing.
=> Fixing Custom Agent Context Missing From getOps/getOpsBulk

package.json
We recently updated `package.json` to only include `lib/` in our
published package in https://github.com/share/sharedb/pull/469
However, the driver libraries run tests from `test/`, which are no
longer included in the package, which has broken downstream builds.
This change re-includes the `test/` directory to fix those builds.
This approximately doubles our package size. If we're concerned about
this, in future we should consider breaking out a separate testing
library (which may also make our library inter-dependency, and testing
strategy a bit more transparent).
=> 🔧 Re-include `test/` folder in package

lib/ot.js, test/ot.js
At the moment, the `ot.applyOps()` duplicates a lot of logic from
`ot.apply()`.
This change refactors `applyOps()` into a simple loop wrapper, and
completely reuses all apply logic from `ot.apply()`.
=> ♻️ Refactor `ot.applyOps()`

lib/backend.js, lib/ot.js, package.json, test/client/snapshot-version-request.js
`json0` recently merged a [breaking change][1] which enforces some
stricter type checking.
Apart from this stricter type checking, no other changes were made, so
any client that only ever submits well-formed ops should be able to
upgrade directly without any trouble.
However, if clients submitted some bad ops (that are no longer allowed
under the stricter checking), then `fetchSnapshot()` will fail when
trying to apply these ops to rebuild the snapshot.
This failure can be surprising if the only "bad" thing about the ops
was that they had [bad path types][2], because at the time when they
were submitted, the snapshot would have been correctly updated.
This change rescues from this particular failure by coercing paths into
the correct type: `number` for arrays, and `string` for objects. …
=> 🥅 Allow fetching historic snapshots with bad `json0` paths

test/client/projections.js
Fixes https://github.com/share/sharedb/issues/503
This change fixes a flaky test, which relies on a `setTimeout` with a
10ms wait.
This change replaces the use of a `setTimeout` with an event listener,
which is not prone to flakiness, and is more semantic.
=> ✅ Fix flaky test

lib/backend.js, lib/ot.js, test/client/snapshot-version-request.js
We recently [added a shim][1] to let consumers bump to a breaking
version of `json0`.
This shim normalized the `json0` path to allow older, less strict ops to
be applied using the stricter version of `json0`.
However, that change also included [stricter checking for `lm`][2].
This change updates our shim to also allow for these older ops. We also
rename our internal methods to be more reflective of the fact that we're
normalizing ops (rather than just their paths).
[1]: https://github.com/share/sharedb/pull/496
[2]: https://github.com/ottypes/json0/pull/40/files#diff-188db14d4925d79e94b18d68782b7df264ff95d95a26812b5b2c07c90f5640afR222-R223
=> 🥅 Normalize `json0` `lm`

.eslintrc.js, package.json
Fixes https://github.com/share/sharedb/issues/509
For some reason, the build has started linting our `/docs/` folder. It's
possible that this was an `eslint` bug, and that it should have always
been linted, since we just use our `.gitignore` file (and the JS in our
docs folder is ignored by its own, nested `.gitignore` file).
This change bumps our version of `eslint`, and adds the `/docs`/ folder
separately to be ignored by `eslint`.
=> 🚨 Ignore docs when linting

docs/api/snapshot.md
`Snapshot.type` should be marked as a `string`, since it's a
serializable form of a `Doc`, and the serializable form of a type is its
URI.
The `snapshot.type` is assumed to be a URI at many points in the code:
- https://github.com/share/sharedb/blob/e29936ca2dffd187b3fcfa3ca1b7e83becb6a2dc/lib/projections.js#L82
- https://github.com/share/sharedb/blob/99ea28e003bdba4e7fcba7c45e70d47f30ea96f5/lib/ot.js#L80
- https://github.com/share/sharedb/blob/e29936ca2dffd187b3fcfa3ca1b7e83becb6a2dc/lib/agent.js#L562-L563
=> 📝 Update `Snapshot` documentation

.github/workflows/test.yml, CHANGELOG.md, package.json
Fixes https://github.com/share/sharedb/issues/483
This is a **BREAKING CHANGE** which drops official Node.js v10 support,
which has been [end-of-lifed][1].
[1]: https://nodejs.org/en/about/releases/
=> 💥 Drop Node v10 support

lib/client/doc.js, package.json, test/client/doc.js
When we had rollbacks due to conflicts on our server, the rollback would fail when the rejected ops were `rich-text` ops, which aren't invertible due to the error in #442.
This fix is a less breaking change than what's proposed in #442, #443, and #451, and can potentially close those issues. Unlike those changes, this change:
1. Doesn't require any changes in libraries to support it
2. Only changes the behaviour in cases that are totally broken today
Closes #442.
When the ops fail to invert, just fall back to a hard rollback (refetching the data from the server)
Added automated test for this case that failed before, but passes now.
=> Fall back to doing a _hardRollback when `op.type.invert` fails

docs/middleware/actions.md, lib/agent.js, lib/backend.js, test/client/presence/presence.js
At the moment, we have a [`sendPresence`][1] middleware hook, which is
triggered just before a presence update is about to be sent to a client.
This existing hook is useful for determining if a client should receive
an update or not on the server.
However, it doesn't let us *stop* clients from broadcasting to other
clients, which we may want to do for authentication reasons, for
example.
This change adds a new `receivePresence` middleware hook, which is
triggered when the server receives a presence message from a client,
before the presence has been transformed against any ops.
Passing an error to this middleware hook will return an error message to
the broadcasting client (as opposed to `sendPresence`, which will send
an error down to any subscribed clients).
[1]: …
=> ✨ Add `receivePresence` middleware hook

docs/api/backend.md, lib/agent.js, lib/backend.js, test/backend.js, test/client/presence/presence.js
At the moment, if an error is passed in the `sendPresence` middleware,
this error is broadcast to any subscribed listeners.
Consumers may wish to use the `sendPresence` middleware to filter
messages being sent to particular clients (eg based on authentication or
other criteria). In these cases, no information at all should be
broadcast to subscribers, since this might be something of a security
risk - a malicious client can tell there's activity on a channel, even
if they don't know exactly what that activity is.
This change deprecates the current error behaviour, and adds a new flag
to opt-in to the new behaviour of emitting errors on `Backend` instead
of sending them down to clients. If consumers haven't actively opted in
for this behaviour, they will get a deprecation warning.
=> 🔒 Prevent sending `sendPresence` middleware errors to subscribers

README.md
This statement in the `README` is now out-of-date (we're on v2).
`sharedb` has been out of beta since [November 2019][1], so we can
probably remove the link to the upgrade guide (which is linked in the
v1.0.0 release notes anyway).
[1]: https://github.com/share/sharedb/releases/tag/v1.0.0
=> 📝 Remove version reference from `README`

lib/client/doc.js, lib/client/presence/local-doc-presence.js, test/client/presence/doc-presence.js
This change fixes a presence edge case:
1. Register a `doc.on('op')` listener which submits presence
2. Create the `LocalPresence` _after_ registering this listener
3. Submit an op
4. The presence being submitted is transformed against the submitted op
when it shouldn't be
This happens because the `LocalPresence` handles its transformation
logic in the `'op'` event. If the `LocalPresence` is created after
another handler that submits presence, then its listener is bound late,
and is only triggered after the handler that submits the op.
The result is that the `LocalPresence` will try to transform the
presence, even though the presence is already consistent with the doc's
state.
We could in theory try to prepend the `LocalPresence` listener, but we'd
still be vulnerable to the same bug if …
=> 🐛 Prevent local presence transformation when presence created late

lib/backend.js, test/client/snapshot-timestamp-request.js, test/client/snapshot-version-request.js, test/ot.js
When calling
```
backend.fetchSnapshotByTimestamp('books', 'mocking-bird', null, next)
```
shareDb was loading the latest milestone snapshot and was not applying
the ops that happen after the milestone.
=> 🐛 Fix issue with null timestamp in fetchSnapshotByTimestamp

examples/rich-text-presence/client.js
This change updates the Presence example to only send Presence updates
when the user actively changes their selection.
Remote clients automatically update Presence when new ops are applied,
so there's no need to send this information.
=> 📝 Update Presence example

lib/client/doc.js, test/client/doc.js
as discussed in https://github.com/share/sharedb/issues/474#issuecomment-1020742910 and https://github.com/share/sharedb/issues/474#issuecomment-1021021414, remote ops should be transformed by ops submitted in `before op` event handler.
=> remote ops are transformed by ops submitted in `before op` event handler

docs/api/backend.md
Fixes https://github.com/share/sharedb/issues/556
=> 📝 Remove `id` from `getOpsBulk()` documentation

docs/api/connection.md
The `Connection`'s `createFetchQuery` and `createSubscribeQuery` take an optional existing result array as `options.results`.
It should be an array of Doc instances:
https://github.com/share/sharedb/blob/1cca122c63329665ebfdeceb1984921badb0cf4d/lib/client/connection.js#L563-L567
This PR updates the docs to indicate the specific type, instead of `Object[]`.
=> [Docs] Indicate create*Query options.results is a Doc[]

package.json
It's best practice to specify a version when depending directly on a
repo.
=> 📌 Pin `json0` dev dependency

lib/client/connection.js, lib/client/doc.js, test/client/doc.js
There's currently an edge case involving trying to get a doc in the middle of being destroyed. For example, consider these synchronous calls:
```js
var doc = connection.get('collection', 'id')
doc.destroy()
var newDoc = connection.get('collection', 'id')
```
Since `Doc` objects are singletons, the above code is effectively the same as:
```js
var doc = connection.get('collection', 'id')
doc.destroy()
var newDoc = doc
```
In other words, our "new" doc is actually already being destroyed, and will soon be removed from the `Connection` cache.
One of the ways this could cause a bug is that the `doc` cannot be found in order to trigger callbacks when receiving responses from the server. `Connection` already tries to handle this case with [`_addDoc()`][1], but this could be problematic for a …
=> 🐛 Allow getting a `Doc` while it's being destroyed

lib/client/connection.js, lib/client/presence/presence.js, test/client/presence/presence.js
There's currently an edge case involving trying to get presence in the middle of being destroyed. For example, consider these synchronous calls:
```js
var presence = connection.getPresence('channel')
presence.destroy()
var newPresence = connection.getPresence('channel')
```
Since `Presence` objects are per-channel singletons, the above code is effectively the same as:
```js
var presence = connection.getPresence('channel')
presence.destroy()
var newPresence = presence
```
In other words, our "new" presence is actually already being destroyed. What's worse, is that if we start trying to create local presence before the `destroy()` callback is triggered, that gets "cleaned up" by the initial call to `destroy()`:
```js
var presence = connection.getPresence('channel')
presence.destroy(() => { …
```
=> 🐛 Allow getting `Presence` while it's being destroyed

.github/workflows/docs.yml
The [`actions/setup-ruby`][1] action has been deprecated and advises moving to [`ruby/setup-ruby`][2]
[1]: https://github.com/actions/setup-ruby
[2]: https://github.com/ruby/setup-ruby
=> 👷‍♀️ Move to `ruby/setup-ruby` action

lib/client/connection.js, lib/client/presence/doc-presence-emitter.js, lib/client/presence/local-doc-presence.js, lib/client/presence/remote-doc-presence.js, test/client/presence/doc-presence-emitter.js, test/client/presence/doc-presence.js
Fixes https://github.com/share/sharedb/issues/584
At the moment, we [attach `Doc` listeners][1] for every remote client in a document (as well as every local user).
This means `Doc`s can quickly hit the [default of 10][2] maximum event listeners.
This change adds a `DocPresenceEmitter` class, which only registers any given `Doc` listener once, regardless of how many presence instances there are. It then forwards events on through its own emitters, which have a much higher value of 1000 max listeners set, in order to avoid too much alert spam, but also keep *some* checking for memory leaks.
[1]: https://github.com/share/sharedb/blob/cc0e3382bf3df4c38c7ccc6bc52da71aff8c9f74/lib/client/presence/remote-doc-presence.js#L42-L47
[2]: https://nodejs.org/api/events.html#eventsdefaultmaxlisteners
=> 🔇 Fix sensitive memory leak warnings when using presence

test/client/query-subscribe.js
Fixes https://github.com/share/sharedb-mongo/issues/131
This change attempts to fix some tests that are flaky in `sharedb-mongo`.
The flakiness can be reproduced locally by wrapping the `Agent._querySubscribe()` [call to `_fetchBulkOps()`][1] in a long `setTimeout()`:
```js
if (options.fetchOps) {
wait++;
setTimeout(function() {
console.log('fetch bulk ops');
agent._fetchBulkOps(collection, options.fetchOps, finish);
}, 1000);
}
```
This forces us into an edge case where the subscribe query triggers and returns the diff from a [`queryPoll()`][2], which triggers the tests' `'insert'` handlers, finishes the test, and closes the backend, all before the `_fetchBulkOps()` call is issued (which subsequently fails because the database has been closed).
Handling this query subscribe actually …
=> ✅ Fix flaky tests

test/milestone-db.js
At the moment we sometimes get some flaky Milestone Mongo test [failures][1].
This potentially happens because milestone snapshots are saved as a [fire-and-forget request][2], which means that we technically make no guarantee about the order that snapshots are written to the database.
Since this is the case, the affected tests may write the v4 snapshot before the others, and then fail assertions about earlier snapshots.
This change tweaks these tests to count the snapshots instead, which should be more robust to this race condition.
[1]: https://github.com/share/sharedb-milestone-mongo/actions/runs/4545270938/jobs/8012439274
[2]: https://github.com/share/sharedb/blob/404cde5568bf88d8de12186a90ba6bc168920e23/lib/submit-request.js#L223
=> ✅ Try to fix flaky Milestone DB tests

.eslintrc.js, .gitignore, examples/counter-json1-vite/.gitignore, examples/counter-json1-vite/index.html, examples/counter-json1-vite/main.js, examples/counter-json1-vite/package.json, examples/counter-json1-vite/server.js, examples/counter-json1-vite/vite.config.js
Towards #593 by cloning the `counter-json1` example and attempting to adapt it to use Vite.
Desired workflows:
* In dev, `npm start` to start the server, then in another terminal/tab `npm run dev` to load the front end with hot reloading enabled (still need to set up the WebSocket proxy for this, but there are blockers in the way of getting to this point)
* In prod `npm run build` followed by `npm start`, like in the other examples.
=> Vite example

lib/agent.js, package.json, test/agent.js, test/setup.js
Fixes https://github.com/share/sharedb/issues/605
At the moment, it's possible for messages to be sent before the client- server handshake.
Sending messages before the handshake has happened has undefined behaviour, and can result in errors such as in:
https://github.com/share/sharedb/issues/605
We can't just ignore these messages, because old clients might potentially be on v1.0 of the client-server protocol, in which the server informs the client when it's ready, but not the other way around, so it's impossible to know when a client should be considered "ready", and its messages acceptable.
Instead, we add a warning for clients on v1.1 who have sent a message before their handshake. In order to aid with debugging, we keep track of the first message received, and log it when the …
=> 🔊 Warn when messages are sent before the v1.1 handshake

docs/getting-started.md, examples/counter-json1-vite/main.js, examples/counter-json1/client.js, examples/counter/client.js, examples/leaderboard/client/connection.js, examples/rich-text-presence/client.js, examples/rich-text/client.js, examples/textarea/client.js
In our docs, we recommend using [`reconnecting-websocket`][1] to handle websocket reconnection.
However, [by default][2] that library will [buffer][3] messages when its underlying socket is closed, which can lead to [undefined behaviour][4] when ShareDB reconnects, since it works under the assumption that all messages sent as the socket is closing have been lost (eg pushing inflight ops back onto the pending queue, etc.).
This change updates our documentation and our examples to set `{maxEnqueuedMessages: 0}`, which disables this buffering, and should help to avoid ShareDB reaching undefined states when reconnecting using this library.
[1]: https://www.npmjs.com/package/reconnecting-websocket
[2]: https://github.com/pladaria/reconnecting-websocket/blob/05a2f7cb0e31f15dff5ff35ad53d07b1bec5e …
=> 📝 Update docs around `reconnecting-websocket`

lib/client/doc.js, test/client/doc.js, test/middleware.js
At the moment, if a client calls `doc.fetch()` with a fetch request already in progress, the client will send a second request, which probably isn't needed (or wanted).
This change prevents duplicate requests from being sent when there's already an inflight fetch request, and adds an internal `force` option, which can be used to force a duplicate request to be sent. This is currently used internally for `_hardRollback()`, which forcibly unsets the `doc.version`, and therefore requires a separate `fetch()` call, since fetch requests are [handled differently][1] depending on the presence of `version`.
[1]: https://github.com/share/sharedb/blob/21750e320f6865ee14620d6bf9610cb7ebc5f18e/lib/agent.js#L607
=> ⚡️ Deduplicate `fetch()` network requests

package.json
In the latest Node 18.17.1 with NPM 6, sharedb fails to install with an "Invalid URL" error.
I traced it back to an attempted parsing of `"npm:sharedb@=1.1.0"`, which is the specifier for the sharedb-legacy devDependency.
According to [node-semver](https://github.com/npm/node-semver#versions):
> A leading `"="` or `"v"` character is stripped off and ignored.
It seems something in the combination of latest Node 18 with NPM 6 isn't stripping the `=`.
Node 18 by default comes with NPM 9, which is why sharedb's CI didn't break. However, NPM 6 is still supported since NPM 7 made some notable breaking changes, and the `=` somehow breaks things even when sharedb is installed as a dependency.
Since the `=` is meaningless in the specifier, removing it fixes the issue and shouldn't affect anything. …
=> Remove extra = in sharedb-legacy devDependency

lib/agent.js
This change adds a `presence.broadcast` `timing` event, which can be used to monitor Presence broadcast performance.
=> 📈 Add `presence.broadcast` `timing` event

lib/agent.js, test/client/presence/presence.js
At the moment, when subscribing a `Presence` multiple times, multiple PubSub `Stream`s are created per-subscription.
However, unsubscribing will only destroy the [last created][1], resulting in streams that are never destroyed.
This change updates our subscription logic to check if we already have an existing stream. If we already have a stream, then we just re-request presence from other clients (which is needed by our [`DocPresence` logic][2]), and return.
Note that we also tweak our unsubscribe logic to eagerly remove the stream after calling destroy (so that subsequent subscribes don't try to reuse a stream that is currently being destroyed).
We also remove a check against `seq`, which is currently not covered by tests (and actually never calls the `callback`), so is clearly broken …
=> ⚡️ Fix Presence `Stream` leak

lib/client/presence/presence.js, lib/client/presence/remote-doc-presence.js
Add a prefix to the `force` option to mark it as internal, so we can remove it later if needed.
=> 🏷️ Mark `presence.subscribe()` options as internal

lib/agent.js, lib/client/connection.js, lib/client/presence/presence.js, lib/client/presence/remote-doc-presence.js, test/client/presence/doc-presence.js, test/client/presence/presence.js
We previously only needed this to re-request presence as part of the `DocPresence` catchup flow.
This change adds an internal method to actively request remote presence for a given channel, and uses that instead of abusing `subscribe()`. This lets us remove the `options` object from `subscribe()`.
=> ♻️ Remove `presence.subscribe()` `force` option

lib/agent.js, test/client/presence/presence.js
The `Agent` stores the most recent presence broadcast sent by a client. However, it eagerly stores this before running the `receivePresence` middleware, which may actually decide that the presence broadcast is invalid (eg malformed, unauthorized, etc.).
This means that the latest cached presence state may not be "legal".
This change moves the caching inside the `trigger()` call, so we only store presence values that have "passed" the middleware.
=> 🐛 Prevent caching presence broadcasts rejected by middleware

.github/workflows/docs.yml
The docs build currently fails with:
```
Run cd docs && gem install bundler && bundle install
ERROR:  Error installing bundler:
The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.4.22. Try installing it with `gem install bundler -v 2.4.22`
```
This change follows the advice of the error message, and specifies the version of bundler to install, since we [can't bump Ruby][1].
[1]: https://pages.github.com/versions/
=> 👷‍♀️ Specify `bundler` version

lib/client/presence/presence.js, test/client/presence/presence.js
There's currently a race condition that can throw uncaught errors when destroying both a `LocalPresence` *and* its parent `Presence` object.
If the `LocalPresence` destroys first, then - since the `Presence` [cached][1] its ID before the `Presence` unsubscribe - by the time the `Presence` tries to destroy its children, the `LocalPresence` is already gone, which throws when [trying to call `destroy()`][2].
This change adds a test for this race condition, and adds a fix, which just checks if the `LocalPresence` still exists on the parent before trying to destroy it.
[1]: https://github.com/share/sharedb/blob/91cae28a0065faf68749243ef36aadf54bf0645d/lib/client/presence/presence.js#L56
[2]: https://github.com/share/sharedb/blob/91cae28a0065faf68749243ef36aadf54bf0645d/lib/client/presence/prese …
=> 🐛 Fix `Presence.destroy()` race condition

lib/op-stream.js, lib/stream-socket.js, lib/util.js
When running ShareDB in a browser environment, we have to polyfill the `util` library.
However, we only use the `inherits` part of that library.
This change will attempt to fall back to the browser-friendly [`inherits` library][1] if `util` can't be found, allowing for lighter polyfilling.
[1]: https://github.com/isaacs/inherits
=> ♻️ Try loading `'inherits'` library if `'util'` is missing

.mocharc.yml, lib/util.js, test/util-test.js
Fixes https://github.com/share/sharedb/issues/646
ShareDB makes heavy use of [`nextTick()`][1]. It notably calls it every time we [send a message over a `StreamSocket`][2].
If ShareDB is running both `Backend` and `Client` in a browser (eg in client tests), `nextTick()` will [fall back to `setTimeout()`][3].
However, according to the [HTML standard][4]:
> Timers can be nested; after five such nested timers, however, the
> interval is forced to be at least four milliseconds.
So using `setTimeout()` can incur a penalty of 4ms in the browser, just idling.
Over the course of a test suite, which makes a lot of fast ShareDB requests in series, these delays can add up to many seconds or even minutes of idle CPU time.
This change adds an alternative `nextTick()` implementation, using …
=> ⚡️ Remove artificial 4ms `nextTick()` delay when running in a browser

lib/backend.js, test/client/snapshot-version-request.js
At the moment, we directly pass our milestone snapshot to `ot.applyOps()`, which [mutates the snapshot][1].
In most Production-grade implementations of the `MilestoneDb`, this is fine, since mutating the in-memory `Snapshot` will have no effect on the underlying database representation.
However, this does break the `MemoryMilestoneDb` (eg in tests).
In order to fix this, and generally be defensive (eg if db adapters decide to implement an in-memory cache), this change clones the snapshot before calling `ot.applyOps()` on it.
[1]: https://github.com/share/sharedb/blob/a5c19b986d65c93abbc9ed11f7a25c0dbaf0788c/lib/ot.js#L172
=> 🐛 Avoid mutating milestone snapshots when building from ops

lib/db/memory.js, test/client/snapshot-version-request.js, test/db-memory.js
It can be useful to delete ops from `MemoryDb` to test how a system will act with TTLed ops.
This change:
- adds a `MemoryDb.deleteOps()` helper method
- adapts `MemoryDb.getOps()` to filter out deleted ops, and check that the correct number of ops are being returned, and error if not (similar to [`sharedb-mongo`][1])
[1]: https://github.com/share/sharedb-mongo/blob/0013d15df717ac8af32aa7847ed64bca96be7f66/index.js#L550
=> ✅ Allow deleting ops in `MemoryDb`

test/client/submit.js
We have [logic][1] that tries to differentiate between:
- a create op that is incorrectly trying to create a `Doc` that already exists
- a create op that has already been committed, and has been resubmitted (possibly because the connection closed before the ack was received)
The latter case is [not currently covered by tests][2].
This change adds a test to cover this branch, and a second similar test which explains why https://github.com/share/sharedb/pull/657 was not a viable change (and correctly fails for that case).
[1]: https://github.com/share/sharedb/blob/7b20313ded4c302b9416cc6c7821694a7fa491b8/lib/submit-request.js#L105-L121
[2]: https://coveralls.io/builds/67552613/source?filename=lib%2Fsubmit-request.js#L117
=> ✅ Add `OP_ALREADY_SUBMITTED` test for create ops

lib/submit-request.js, test/client/submit.js
Supersedes https://github.com/share/sharedb/pull/657
The `DB.getCommitedOpVersion()` function is only used [in one place][1]: in a corner case that differentiates between two "blind", versionless (created without first fetching) create op conflict cases:
- a versionless create op that conflicts with another create op
- a versionless create op that has been re-submitted because the connection was closed before the ack was received
The first of these cases should result in an error, and the second is non-fatal and the error can be swallowed.
At the moment, this differentiation is made using the special `DB.getCommittedOpVersion()` function, which - given an op with a `src` and `seq` combination - will return `null` if the op hasn't been committed, or its version number if it has.
If the op …
=> 🗃 Add `_create` metadata to snapshots to avoid `getCommittedOpVersion()`

test/client/submit.js
One of our tests currently checks resubmitting a create op after reconnecting during submission.
However, since reconnection happens so quickly, this test case can cause two commit attempts in parallel.
We currently only wait for the first request to resolve, which means that the second request can continue into the next test, causing unexpected test failures.
This change waits for both acks to be sent before finishing the test.
=> ✅ Fix create resubmit test

test/client/submit.js
We've had some issues with state from one test bleeding into another.
This happens because all of our `submit.js` tests use the same collection and ID.
This change makes them instead use sequential IDs for each test, which should give each test better isolation from other tests.
=> ✅ Unique ID per test in `submit` tests

lib/submit-request.js, test/client/submit.js
We're currently not returning errors from the database adapter if there are issues fetching the committed op, because of a code typo.
This change adds coverage for this case and fixes the bug.
=> 🐛 Fix error handling in `_fetchCreateOpVersion()`

test/client/query.js, test/client/submit.js, test/db.js
The `getQuery` test option is optional, but the projections tests try to run regardless of whether it's set.
This change moves it inside the guard for this option.
=> ✅ Move projections test inside `getQuery` check

docs/middleware/actions.md
Fixes https://github.com/share/sharedb/issues/668
I'd incorrectly tried to commonise some documentation that includes interpolated text.
It looks like [this has never worked][1], so this change just puts the copy back into the body of the page, and - rather than duplicate - links from other sections to the first place it's used.
[1]: https://github.com/jekyll/jekyll/issues/6815
=> 📝 Fix links in interpolated documentation

lib/client/doc.js, test/client/doc.js
I encountered a situation in ShareDB where my callbacks are often executed in the wrong order.
I tracked this down to incorrect behavior in the `doc.fetch()` method, which pushes the `inflightCallback` onto the back of the `callbacks` array. If there are already any `pendingCallbacks` in the array, then the `inflightCallback` will be executed AFTER all the `pendingCallbacks`.
This is obviously not the desired behavior. The `inflightCallback` should always be executed FIRST, before any of the `pendingCallbacks`.
I fixed the code and wrote a test demonstrating the fix. If you remove my bugfix and run the test, you'll see that it reliably fails.
=> 🐛 Fix inflight/pending callbacks execute in wrong order

lib/agent.js, test/client/presence/doc-presence.js
At the moment, when sending a presence update to other subscribers, we [call `transformPresenceToLatestVersion()`][1] for every presence update which internally [calls `getOps()`][2] for every presence update.
Calls to `getOps()` can be expensive, and rapid presence updates may cause undue load on the server, even when the `Doc` has not been updated.
This change tries to mitigate this by subscribing to a pubsub stream for any `Doc`s that an `Agent` tries to broadcast presence on. We keep an in-memory cache of the latest snapshot version sent over this stream, which lets us quickly check if a presence broadcast is already current without needing to query the database at all.
To avoid leaking streams, the `Agent` will internally handle its stream subscription state by:
- subscribing …
=> ⚡️ Cache latest op version when broadcasting presence

lib/agent.js, lib/client/connection.js, lib/protocol.js, test/agent.js, test/protocol.js
When developing new features, it will be useful to be able to compare server and client protocol versions.
For example, if a server is ahead of an old client, the server could gracefully degrade performance for clients that don't support the new functionality.
This change stores the client's protocol on the `Agent` so we can perform these checks.
We also add a `checkAtLeast()` protocol helper function, and store the current protocol in a constant to avoid magic numbers.
=> ✨ Store client protocol on `Agent`

lib/agent.js, test/client/query-subscribe.js
The `Agent` attempts to check if it's been closed when getting the response for a query subscribe.
However, it incorrectly tries to access `this` inside a `function`, which doesn't give the correct value, and in `strict mode`, will actually result in an error, since `this` will be `undefined`.
This change adds a test for this case and fixes it.
=> 🐛 Fix `closed` check when handling `querySubscribe()`

lib/client/doc.js
At the moment in constructor we call
```js
this.type = null
```
twice. Let's remove one of the calls
=> 🔥 Remove duplicate this.type = null assigment

lib/client/presence/local-doc-presence.js, test/client/presence/doc-presence.js
Similar case to:
- https://github.com/share/sharedb/pull/692
however instead of submitting ops to doc is when we submit doc presence
=>  🐛 Wrong error when submitting presence during hard rollback.
